name: PR Issue Auto-Assignment
on:
  pull_request_target:
    types: [opened, reopened, closed]
permissions:
  contents: read
  issues: write
  pull-requests: read
concurrency:
  group: bot-autoassign-pr-link-${{ github.repository }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  auto-assign-issue:
    if: github.event.action != 'closed' || github.event.pull_request.merged == false
    uses: Eeshu-Yadav/openwisp-utils/.github/workflows/reusable-bot-autoassign.yml@issues/649-fix-bot-assignment-silent-failure
    with:
      bot_command: issue_assignment
    secrets:
      OPENWISP_BOT_APP_ID: ${{ secrets.OPENWISP_BOT_APP_ID }}
      OPENWISP_BOT_PRIVATE_KEY: ${{ secrets.OPENWISP_BOT_PRIVATE_KEY }}
